---
kind: Template
apiVersion: v1
metadata:
  name: filter-s2
  annotations:
    openshift.io/display-name: filter-s2
    description: >-
      The templates instantiates the gateway for openEO on OpenShift Origin.
    openshift.io/long-description: >-
      Multiple services are setup to provide the OpenEO capabilities. For setting up a
      OpenShift cluster and configure persitant storage please read the OpenShift documentation.
      Fur further information on OpenEO please have a look at http://openeo.org
    tags: openeo, openshift, python, flask
    iconClass: icon-python
labels:
  application: filter-s2
  provider: openeo
  project: openeo
  app: filter-s2
  version: 0.0.1
message: "The openEO template will be instantiated." 

parameters:
- name: IMAGE_NAME
  displayName: Image Name
  value: filter-s2
  required: true
- name: GIT_URI
  displayName: Git URI
  value: https://github.com/Open-EO/openeo-openshift-driver.git
  required: true
- name: GIT_REF
  displayName: Git Directory
  value: release-0.0.2
  required: true
- name: GIT_DIR
  displayName: Git Directory
  value: operations/filter-s2
  required: true

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${IMAGE_NAME}"
  spec:
    dockerImageRepository:
    tags:
    - name: latest

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${IMAGE_NAME}"
  spec:
    source:
      type: Git
      git:
        uri: "${GIT_URI}"
        ref: "${GIT_REF}"
      contextDir: "${GIT_DIR}"
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: "${IMAGE_NAME}:latest"
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: